// Generated by gencpp from file anm_msgs/CommandCheckingReport.msg
// DO NOT EDIT!


#ifndef ANM_MSGS_MESSAGE_COMMANDCHECKINGREPORT_H
#define ANM_MSGS_MESSAGE_COMMANDCHECKINGREPORT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace anm_msgs
{
template <class ContainerAllocator>
struct CommandCheckingReport_
{
  typedef CommandCheckingReport_<ContainerAllocator> Type;

  CommandCheckingReport_()
    : error_message()
    , error_code(0)  {
    }
  CommandCheckingReport_(const ContainerAllocator& _alloc)
    : error_message(_alloc)
    , error_code(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _error_message_type;
  _error_message_type error_message;

   typedef int16_t _error_code_type;
  _error_code_type error_code;





  typedef boost::shared_ptr< ::anm_msgs::CommandCheckingReport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anm_msgs::CommandCheckingReport_<ContainerAllocator> const> ConstPtr;

}; // struct CommandCheckingReport_

typedef ::anm_msgs::CommandCheckingReport_<std::allocator<void> > CommandCheckingReport;

typedef boost::shared_ptr< ::anm_msgs::CommandCheckingReport > CommandCheckingReportPtr;
typedef boost::shared_ptr< ::anm_msgs::CommandCheckingReport const> CommandCheckingReportConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anm_msgs::CommandCheckingReport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anm_msgs::CommandCheckingReport_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace anm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'dbw_mkz_msgs': ['/home/sundong/Exploring/localplanning/ros_navigation_stack_vrep_simulation/vrep_ws/src/ivrc_msg/dbw_mkz_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'anm_msgs': ['/home/sundong/Exploring/localplanning/ros_navigation_stack_vrep_simulation/vrep_ws/src/ivrc_msg/anm_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::anm_msgs::CommandCheckingReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anm_msgs::CommandCheckingReport_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anm_msgs::CommandCheckingReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anm_msgs::CommandCheckingReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anm_msgs::CommandCheckingReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anm_msgs::CommandCheckingReport_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anm_msgs::CommandCheckingReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e493a4ffb569d2d770774c27d6f3ed0c";
  }

  static const char* value(const ::anm_msgs::CommandCheckingReport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe493a4ffb569d2d7ULL;
  static const uint64_t static_value2 = 0x70774c27d6f3ed0cULL;
};

template<class ContainerAllocator>
struct DataType< ::anm_msgs::CommandCheckingReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anm_msgs/CommandCheckingReport";
  }

  static const char* value(const ::anm_msgs::CommandCheckingReport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anm_msgs::CommandCheckingReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message acts as a report from the command_checking node to broadcast\n\
# any errors detected in the control commands\n\
\n\
std_msgs/String error_message\n\
int16 error_code\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::anm_msgs::CommandCheckingReport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anm_msgs::CommandCheckingReport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_message);
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandCheckingReport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anm_msgs::CommandCheckingReport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anm_msgs::CommandCheckingReport_<ContainerAllocator>& v)
  {
    s << indent << "error_message: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.error_message);
    s << indent << "error_code: ";
    Printer<int16_t>::stream(s, indent + "  ", v.error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANM_MSGS_MESSAGE_COMMANDCHECKINGREPORT_H
