// Generated by gencpp from file anm_msgs/DynamicObstacleList.msg
// DO NOT EDIT!


#ifndef ANM_MSGS_MESSAGE_DYNAMICOBSTACLELIST_H
#define ANM_MSGS_MESSAGE_DYNAMICOBSTACLELIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <anm_msgs/DynamicObstacle.h>

namespace anm_msgs
{
template <class ContainerAllocator>
struct DynamicObstacleList_
{
  typedef DynamicObstacleList_<ContainerAllocator> Type;

  DynamicObstacleList_()
    : header()
    , obstacles()  {
    }
  DynamicObstacleList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::anm_msgs::DynamicObstacle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::anm_msgs::DynamicObstacle_<ContainerAllocator> >::other >  _obstacles_type;
  _obstacles_type obstacles;





  typedef boost::shared_ptr< ::anm_msgs::DynamicObstacleList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anm_msgs::DynamicObstacleList_<ContainerAllocator> const> ConstPtr;

}; // struct DynamicObstacleList_

typedef ::anm_msgs::DynamicObstacleList_<std::allocator<void> > DynamicObstacleList;

typedef boost::shared_ptr< ::anm_msgs::DynamicObstacleList > DynamicObstacleListPtr;
typedef boost::shared_ptr< ::anm_msgs::DynamicObstacleList const> DynamicObstacleListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anm_msgs::DynamicObstacleList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anm_msgs::DynamicObstacleList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace anm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'dbw_mkz_msgs': ['/home/sundong/Exploring/localplanning/ros_navigation_stack_vrep_simulation/vrep_ws/src/ivrc_msg/dbw_mkz_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'anm_msgs': ['/home/sundong/Exploring/localplanning/ros_navigation_stack_vrep_simulation/vrep_ws/src/ivrc_msg/anm_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::anm_msgs::DynamicObstacleList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anm_msgs::DynamicObstacleList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anm_msgs::DynamicObstacleList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anm_msgs::DynamicObstacleList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anm_msgs::DynamicObstacleList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anm_msgs::DynamicObstacleList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anm_msgs::DynamicObstacleList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3435c2c322edb674d240f51d9feb64aa";
  }

  static const char* value(const ::anm_msgs::DynamicObstacleList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3435c2c322edb674ULL;
  static const uint64_t static_value2 = 0xd240f51d9feb64aaULL;
};

template<class ContainerAllocator>
struct DataType< ::anm_msgs::DynamicObstacleList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anm_msgs/DynamicObstacleList";
  }

  static const char* value(const ::anm_msgs::DynamicObstacleList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anm_msgs::DynamicObstacleList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Dynamic obstacle list custom message \n\
Header header\n\
anm_msgs/DynamicObstacle[] obstacles\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: anm_msgs/DynamicObstacle\n\
# This message decribes the information of dynamic obstacles in odom frame \n\
# position       =  The recent position of the dynamic obstacle(centroid of the object)\n\
# dimensions     =  The bounding box size:  length(along heading direction), width and height \n\
# speed          =  The speed of the car along the heading direction.\n\
# yaw            =  The recent heading of the car.  \n\
\n\
geometry_msgs/Point position\n\
geometry_msgs/Vector3 dimensions   # length width and height\n\
float32 speed\n\
float32 yaw \n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::anm_msgs::DynamicObstacleList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anm_msgs::DynamicObstacleList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DynamicObstacleList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anm_msgs::DynamicObstacleList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anm_msgs::DynamicObstacleList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "obstacles[]" << std::endl;
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      s << indent << "  obstacles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::anm_msgs::DynamicObstacle_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANM_MSGS_MESSAGE_DYNAMICOBSTACLELIST_H
