// Generated by gencpp from file anm_msgs/HMIReport.msg
// DO NOT EDIT!


#ifndef ANM_MSGS_MESSAGE_HMIREPORT_H
#define ANM_MSGS_MESSAGE_HMIREPORT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace anm_msgs
{
template <class ContainerAllocator>
struct HMIReport_
{
  typedef HMIReport_<ContainerAllocator> Type;

  HMIReport_()
    : header()
    , auto_toggle_pressed(0)
    , manual_estop_pressed(0)
    , auto_engage_pressed(0)
    , auto_disengage_pressed(0)
    , environment_checks_pressed(0)
    , system_checks_pressed(0)
    , emergency_pullover_exit_pressed(0)
    , manual_drive_pressed(0)
    , gear_change_pressed(0)
    , auto_toggle(0)
    , manual_estop(0)
    , environment_checks(0)
    , system_checks(0)
    , emergency_pullover_exit(0)
    , gear_setting(0)  {
    }
  HMIReport_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , auto_toggle_pressed(0)
    , manual_estop_pressed(0)
    , auto_engage_pressed(0)
    , auto_disengage_pressed(0)
    , environment_checks_pressed(0)
    , system_checks_pressed(0)
    , emergency_pullover_exit_pressed(0)
    , manual_drive_pressed(0)
    , gear_change_pressed(0)
    , auto_toggle(0)
    , manual_estop(0)
    , environment_checks(0)
    , system_checks(0)
    , emergency_pullover_exit(0)
    , gear_setting(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _auto_toggle_pressed_type;
  _auto_toggle_pressed_type auto_toggle_pressed;

   typedef uint8_t _manual_estop_pressed_type;
  _manual_estop_pressed_type manual_estop_pressed;

   typedef uint8_t _auto_engage_pressed_type;
  _auto_engage_pressed_type auto_engage_pressed;

   typedef uint8_t _auto_disengage_pressed_type;
  _auto_disengage_pressed_type auto_disengage_pressed;

   typedef uint8_t _environment_checks_pressed_type;
  _environment_checks_pressed_type environment_checks_pressed;

   typedef uint8_t _system_checks_pressed_type;
  _system_checks_pressed_type system_checks_pressed;

   typedef uint8_t _emergency_pullover_exit_pressed_type;
  _emergency_pullover_exit_pressed_type emergency_pullover_exit_pressed;

   typedef uint8_t _manual_drive_pressed_type;
  _manual_drive_pressed_type manual_drive_pressed;

   typedef uint8_t _gear_change_pressed_type;
  _gear_change_pressed_type gear_change_pressed;

   typedef uint8_t _auto_toggle_type;
  _auto_toggle_type auto_toggle;

   typedef uint8_t _manual_estop_type;
  _manual_estop_type manual_estop;

   typedef uint8_t _environment_checks_type;
  _environment_checks_type environment_checks;

   typedef uint8_t _system_checks_type;
  _system_checks_type system_checks;

   typedef uint8_t _emergency_pullover_exit_type;
  _emergency_pullover_exit_type emergency_pullover_exit;

   typedef uint8_t _gear_setting_type;
  _gear_setting_type gear_setting;





  typedef boost::shared_ptr< ::anm_msgs::HMIReport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anm_msgs::HMIReport_<ContainerAllocator> const> ConstPtr;

}; // struct HMIReport_

typedef ::anm_msgs::HMIReport_<std::allocator<void> > HMIReport;

typedef boost::shared_ptr< ::anm_msgs::HMIReport > HMIReportPtr;
typedef boost::shared_ptr< ::anm_msgs::HMIReport const> HMIReportConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anm_msgs::HMIReport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anm_msgs::HMIReport_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace anm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'dbw_mkz_msgs': ['/home/sundong/Exploring/localplanning/ros_navigation_stack_vrep_simulation/vrep_ws/src/ivrc_msg/dbw_mkz_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'anm_msgs': ['/home/sundong/Exploring/localplanning/ros_navigation_stack_vrep_simulation/vrep_ws/src/ivrc_msg/anm_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::anm_msgs::HMIReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anm_msgs::HMIReport_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anm_msgs::HMIReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anm_msgs::HMIReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anm_msgs::HMIReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anm_msgs::HMIReport_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anm_msgs::HMIReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "515b6d3b9f37b3178d08258bc23fa8f9";
  }

  static const char* value(const ::anm_msgs::HMIReport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x515b6d3b9f37b317ULL;
  static const uint64_t static_value2 = 0x8d08258bc23fa8f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::anm_msgs::HMIReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anm_msgs/HMIReport";
  }

  static const char* value(const ::anm_msgs::HMIReport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anm_msgs::HMIReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message indicates input changes on the HMI\n\
# Any field with an '_pressed' at the end is a button update (1 = update, 0 = not)\n\
# Any field after with a 1 means PASS/ON/SET, and 0 means FAIIL/OFF/UNSET (except gear change)\n\
# For gear change, 0=park, 1=drive, 2=reverse, 3=neutral, 4=low\n\
\n\
Header header\n\
uint8 auto_toggle_pressed\n\
uint8 manual_estop_pressed\n\
uint8 auto_engage_pressed\n\
uint8 auto_disengage_pressed\n\
uint8 environment_checks_pressed\n\
uint8 system_checks_pressed\n\
uint8 emergency_pullover_exit_pressed\n\
uint8 manual_drive_pressed\n\
uint8 gear_change_pressed\n\
uint8 auto_toggle\n\
uint8 manual_estop\n\
uint8 environment_checks\n\
uint8 system_checks\n\
uint8 emergency_pullover_exit\n\
uint8 gear_setting\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::anm_msgs::HMIReport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anm_msgs::HMIReport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.auto_toggle_pressed);
      stream.next(m.manual_estop_pressed);
      stream.next(m.auto_engage_pressed);
      stream.next(m.auto_disengage_pressed);
      stream.next(m.environment_checks_pressed);
      stream.next(m.system_checks_pressed);
      stream.next(m.emergency_pullover_exit_pressed);
      stream.next(m.manual_drive_pressed);
      stream.next(m.gear_change_pressed);
      stream.next(m.auto_toggle);
      stream.next(m.manual_estop);
      stream.next(m.environment_checks);
      stream.next(m.system_checks);
      stream.next(m.emergency_pullover_exit);
      stream.next(m.gear_setting);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HMIReport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anm_msgs::HMIReport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anm_msgs::HMIReport_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "auto_toggle_pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.auto_toggle_pressed);
    s << indent << "manual_estop_pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.manual_estop_pressed);
    s << indent << "auto_engage_pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.auto_engage_pressed);
    s << indent << "auto_disengage_pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.auto_disengage_pressed);
    s << indent << "environment_checks_pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.environment_checks_pressed);
    s << indent << "system_checks_pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.system_checks_pressed);
    s << indent << "emergency_pullover_exit_pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emergency_pullover_exit_pressed);
    s << indent << "manual_drive_pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.manual_drive_pressed);
    s << indent << "gear_change_pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear_change_pressed);
    s << indent << "auto_toggle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.auto_toggle);
    s << indent << "manual_estop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.manual_estop);
    s << indent << "environment_checks: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.environment_checks);
    s << indent << "system_checks: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.system_checks);
    s << indent << "emergency_pullover_exit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emergency_pullover_exit);
    s << indent << "gear_setting: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear_setting);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANM_MSGS_MESSAGE_HMIREPORT_H
