# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from anm_msgs/V2XVehicle.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class V2XVehicle(genpy.Message):
  _md5sum = "37f8e1d7c4cd5cf2bc765b7f1a716323"
  _type = "anm_msgs/V2XVehicle"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Vehicle v2x custom header
#
# id       = ID of vehicle
# position = x y position in odom frame (meters)
# speed    = speed of the vehicle (meters/second)
# yaw      = heading in radians north of east
# self     = if this is the local vehicle, true, otherwise, false

uint32 id
geometry_msgs/Point position
float64 speed
float64 yaw
bool is_self

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['id','position','speed','yaw','is_self']
  _slot_types = ['uint32','geometry_msgs/Point','float64','float64','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,position,speed,yaw,is_self

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(V2XVehicle, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.speed is None:
        self.speed = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.is_self is None:
        self.is_self = False
    else:
      self.id = 0
      self.position = geometry_msgs.msg.Point()
      self.speed = 0.
      self.yaw = 0.
      self.is_self = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_I5dB().pack(_x.id, _x.position.x, _x.position.y, _x.position.z, _x.speed, _x.yaw, _x.is_self))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 45
      (_x.id, _x.position.x, _x.position.y, _x.position.z, _x.speed, _x.yaw, _x.is_self,) = _get_struct_I5dB().unpack(str[start:end])
      self.is_self = bool(self.is_self)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_I5dB().pack(_x.id, _x.position.x, _x.position.y, _x.position.z, _x.speed, _x.yaw, _x.is_self))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 45
      (_x.id, _x.position.x, _x.position.y, _x.position.z, _x.speed, _x.yaw, _x.is_self,) = _get_struct_I5dB().unpack(str[start:end])
      self.is_self = bool(self.is_self)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_I5dB = None
def _get_struct_I5dB():
    global _struct_I5dB
    if _struct_I5dB is None:
        _struct_I5dB = struct.Struct("<I5dB")
    return _struct_I5dB
