// Generated by gencpp from file vrep_skeleton_msg_and_srv/displayText.msg
// DO NOT EDIT!


#ifndef VREP_SKELETON_MSG_AND_SRV_MESSAGE_DISPLAYTEXT_H
#define VREP_SKELETON_MSG_AND_SRV_MESSAGE_DISPLAYTEXT_H

#include <ros/service_traits.h>


#include <vrep_skeleton_msg_and_srv/displayTextRequest.h>
#include <vrep_skeleton_msg_and_srv/displayTextResponse.h>


namespace vrep_skeleton_msg_and_srv
{

struct displayText
{

typedef displayTextRequest Request;
typedef displayTextResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct displayText
} // namespace vrep_skeleton_msg_and_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_skeleton_msg_and_srv::displayText > {
  static const char* value()
  {
    return "d53844fdc821fc6baaf569373762bd8b";
  }

  static const char* value(const ::vrep_skeleton_msg_and_srv::displayText&) { return value(); }
};

template<>
struct DataType< ::vrep_skeleton_msg_and_srv::displayText > {
  static const char* value()
  {
    return "vrep_skeleton_msg_and_srv/displayText";
  }

  static const char* value(const ::vrep_skeleton_msg_and_srv::displayText&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_skeleton_msg_and_srv::displayTextRequest> should match 
// service_traits::MD5Sum< ::vrep_skeleton_msg_and_srv::displayText > 
template<>
struct MD5Sum< ::vrep_skeleton_msg_and_srv::displayTextRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_skeleton_msg_and_srv::displayText >::value();
  }
  static const char* value(const ::vrep_skeleton_msg_and_srv::displayTextRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_skeleton_msg_and_srv::displayTextRequest> should match 
// service_traits::DataType< ::vrep_skeleton_msg_and_srv::displayText > 
template<>
struct DataType< ::vrep_skeleton_msg_and_srv::displayTextRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_skeleton_msg_and_srv::displayText >::value();
  }
  static const char* value(const ::vrep_skeleton_msg_and_srv::displayTextRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_skeleton_msg_and_srv::displayTextResponse> should match 
// service_traits::MD5Sum< ::vrep_skeleton_msg_and_srv::displayText > 
template<>
struct MD5Sum< ::vrep_skeleton_msg_and_srv::displayTextResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_skeleton_msg_and_srv::displayText >::value();
  }
  static const char* value(const ::vrep_skeleton_msg_and_srv::displayTextResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_skeleton_msg_and_srv::displayTextResponse> should match 
// service_traits::DataType< ::vrep_skeleton_msg_and_srv::displayText > 
template<>
struct DataType< ::vrep_skeleton_msg_and_srv::displayTextResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_skeleton_msg_and_srv::displayText >::value();
  }
  static const char* value(const ::vrep_skeleton_msg_and_srv::displayTextResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_SKELETON_MSG_AND_SRV_MESSAGE_DISPLAYTEXT_H
